server:
  port: 8111

person:
  name: guozhihao${random.uuid}
  age: ${random.int}
  happy: false
  birth: 1991/06/17
  email: 123@qq.com
  maps: {k1: v1, k2: v2}
  #  dog-name: 狗
  hobby-list:
    - code
    - music
    - dota2
  dog:
    name: ${person.dog-name:猫咪}
    age: 1
