server:
  port: 8115
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.gzh.springbootshiro.entity
  mapper-locations: classpath:mybatis/mapper/*.xml